# Exercise 5.A NumPy Fundamentals
## Author: Cagla Celik
This notebook explores the basics of NumPy arrays including creation,
indexing, slicing, and array dimensions.

In [1]:
import numpy as np

## Array Basics

In [2]:
fruits = ['apple', 'banana', 'cherry', 'date']

In [3]:
arr_1 = np.array(fruits)
print(arr_1)

['apple' 'banana' 'cherry' 'date']


In [4]:
print(arr_1.dtype)
# The letter 'U' means Unicode string (text data)
# The number after U is the length of the longest string in the array

<U6


In [5]:
arr_2 = np.array([(10, 11, 12), (13, 14, 15)])
print(arr_2)

[[10 11 12]
 [13 14 15]]


In [6]:
print(arr_2.T)

[[10 13]
 [11 14]
 [12 15]]


In [7]:
print(arr_2)
# No! .T does not change the original array, it just displays it transposed.
# arr_2 still has its original shape.

[[10 11 12]
 [13 14 15]]


In [8]:
arr_3 = np.array([(1, 3, 5), (2, 4, 6)])
print(arr_3)

[[1 3 5]
 [2 4 6]]


In [9]:
arr_4 = np.array([arr_3[0, 2], arr_3[1, 1]])
print(arr_4)
# arr_3[0,2] = 5 (row 0, column 2)
# arr_3[1,1] = 4 (row 1, column 1)

[5 4]


In [10]:
arr_5 = np.ones((2, 2, 2))
print(arr_5)
# A 3D array with two values in each dimension, all filled with 1s

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
