# Exercise 1.A NumPy: Manipulating Arrays

In [3]:
import numpy as np

## Looping Through Arrays

In [5]:
arrA = np.array([[11, 12, 13], [14, 15, 16]])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [6]:
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [7]:
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


## The first loop prints each row multiplied by 2. The second loop prints each individual number multiplied by 2.

In [9]:
for x in arrA:
    loop_result = x * 2
    print(loop_result)
# loop_result gets overwritten each loop. It only holds the last row's result

[22 24 26]
[28 30 32]


In [10]:
joined_array_1 = np.concatenate((arrA, arrA), axis=0)
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [11]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [12]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [13]:
# This will throw an error — arrays must be the same shape to stack
stacked_array_2 = np.stack((joined_array_1, joined_array_2))
# Error: all input arrays must have the same shape

ValueError: all input arrays must have the same shape

In [14]:
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [15]:
# This will error — axis=1 means columns must match in row count
another_2 = np.concatenate((joined_array_1, arrA), axis=1)
# Error: arrays must have the same number of rows to join on axis=1

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [17]:
h = np.hstack((arrA, arrA))   # side by side (like axis=1)
v = np.vstack((arrA, arrA))   # top to bottom (like axis=0)
d = np.dstack((arrA, arrA))   # depth to wise (adds a 3rd dimension)
print(h)
print(v)
print(d)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]
[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]
[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splitting Arrays

In [20]:
splitsky = np.split(joined_array_1, 2)
print(splitsky)
# Result: 2 arrays, each with 2 rows (2D)

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [22]:
spliterino = np.split(joined_array_1, 3)
print(spliterino)
# Error: 4 rows can't be divided equally into 3 parts

ValueError: array split does not result in an equal division

## Searching and Replacing Array Values

In [23]:
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')
print(result_1)
# arrA % 2 == 0 checks if a number is even (no remainder when divided by 2)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

In [24]:
arrB = np.array([[7, 6], [13, 5], [7, 3]])
arrB_sorted = np.sort(arrB)
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [25]:
print(arrB)
z = arrB < 7
arrC = arrB[z]
print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [26]:
y = arrB >= 7
arrD = arrB[y]
print(arrD)

[ 7 13  7]
