# Exercise 1.B NumPy Random

In [1]:
import numpy as np

## Generating Random Numbers

In [2]:
r_1 = np.random.randint(1, 20, size=2)
print(r_1)

[2 3]


In [3]:
r_2 = np.random.randint(1, 20, size=(1, 2))
print(r_2)

[[18  3]]


In [4]:
r_3 = np.random.random(size=(2, 1))
print(r_3)

[[0.86622311]
 [0.7923237 ]]


In [5]:
r_4 = np.random.randint(20, 100, size=(4, 5))
print(r_4)

[[67 20 42 35 48]
 [24 64 31 86 83]
 [66 55 99 61 21]
 [41 61 63 34 68]]


In [6]:
r_5 = np.random.random(size=(4, 5))
print(r_5)

[[0.03450693 0.1994779  0.94666534 0.61552552 0.79423387]
 [0.6524898  0.49146959 0.38962526 0.83638002 0.73590042]
 [0.57157285 0.87306365 0.74459637 0.73365634 0.54888868]
 [0.80970833 0.34385192 0.70981806 0.68712704 0.85212303]]


## Generating Random Choices from an Array

In [7]:
students = np.array(['Alice', 'Bob', 'Carlos', 'Diana', 'Eve', 'Frank',
                     'Grace', 'Hector', 'Iris', 'James', 'Karen', 'Leo'])

In [11]:
call_on = np.random.choice(students)
print(call_on)

Leo


In [13]:
breakout_groups = np.random.choice(students, size=(3, 4))
print(breakout_groups)
# Not ideal for breakout groups. The same student can appear more than once

[['James' 'Alice' 'Carlos' 'James']
 ['Grace' 'Iris' 'Hector' 'Carlos']
 ['Diana' 'Frank' 'James' 'Frank']]


In [15]:
call_on_weighted = np.random.choice(students, size=5, p=[0.30, 0.10, 0.10, 0.10, 0.10,
                                                          0.05, 0.05, 0.05, 0.05, 0.05,
                                                          0.05, 0.00])
print(call_on_weighted)
# Alice has 30% chance, Leo has 0% chance, others share the remaining 70%

['Karen' 'Diana' 'Carlos' 'Carlos' 'Eve']


## Generating a Normal Distribution

In [17]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))
print(bell_curve)

[[17.62308773 11.08903007 14.72539676 13.81860179 11.56454331]
 [12.80558763  4.71026781 10.45944737 18.97034986  7.85502053]
 [11.96088092  3.74170871  4.86919681 14.49760614 14.84892659]
 [ 8.83284911  4.22446944  1.83982885  7.02900501 12.32056081]]
