# Exercise 1.C Performing operations on arrays

In [1]:
import numpy as np

## Sample Arrays

In [3]:
r_1 = np.random.randint(1, 20, size=2)
r_2 = np.random.randint(1, 20, size=(1, 2))
r_3 = np.random.random(size=(2, 1))
r_4 = np.random.randint(20, 100, size=(4, 5))
r_5 = np.random.random(size=(4, 5))

## Permutations

In [4]:
print(r_4)

[[90 85 81 78 68]
 [72 23 60 36 48]
 [41 50 88 86 91]
 [65 63 34 57 47]]


In [8]:
np.random.shuffle(r_4)
print(r_4)
# shuffle mixes the ROWS but keeps each row intact

[[90 85 81 78 68]
 [72 23 60 36 48]
 [65 63 34 57 47]
 [41 50 88 86 91]]


Shuffle rearranged the rows of r_4 but kept the values within each row in the same order.

In [11]:
new_shuffle = np.random.permutation(r_4)
print(new_shuffle)
print(r_4)
# permutation returns a NEW shuffled array and r_4 itself stays unchanged

[[72 23 60 36 48]
 [41 50 88 86 91]
 [65 63 34 57 47]
 [90 85 81 78 68]]
[[90 85 81 78 68]
 [72 23 60 36 48]
 [65 63 34 57 47]
 [41 50 88 86 91]]


Use shuffle when you want to mix the original array in place.
Use permutation when you want a shuffled copy without changing the original.

## Mathematical Operations

In [12]:
print(r_1, r_1.shape)
print(r_2, r_2.shape)
print(np.add(r_1, r_2))
print(np.add(r_1, r_2).shape)

[19 12] (2,)
[[ 7 14]] (1, 2)
[[26 26]]
(1, 2)


In [13]:
print(r_1, r_1.shape)
print(r_3, r_3.shape)
print(np.add(r_1, r_3))
print(np.add(r_1, r_3).shape)

[19 12] (2,)
[[0.01516974]
 [0.36464491]] (2, 1)
[[19.01516974 12.01516974]
 [19.36464491 12.36464491]]
(2, 2)


In [16]:
print(r_2, r_2.shape)
print(r_4, r_4.shape)
print(np.add(r_2, r_4))
print(np.add(r_2, r_4).shape)
# ValueError: r_2 has 2 columns and r_4 has 5 columns. Can't broadcast together

[[ 7 14]] (1, 2)
[[90 85 81 78 68]
 [72 23 60 36 48]
 [65 63 34 57 47]
 [41 50 88 86 91]] (4, 5)


ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

In [17]:
# np.add(r_1, r_4) throws an error : shapes (2,) and (4,5) are not compatible
# np.add(r_2, r_3) also errors : (1,2) and (2,1) don't broadcast together
print(np.add(r_1, r_4))

ValueError: operands could not be broadcast together with shapes (2,) (4,5) 

In [18]:
print(np.add(np.array([1]), r_4))
# Adds 1 to every element in r_4

[[91 86 82 79 69]
 [73 24 61 37 49]
 [66 64 35 58 48]
 [42 51 89 87 92]]


In [19]:
print(np.add(np.array([[1]]), r_4))
# Same result. [[1]] broadcasts across all rows and columns

[[91 86 82 79 69]
 [73 24 61 37 49]
 [66 64 35 58 48]
 [42 51 89 87 92]]


In [20]:
print(np.add(np.array([1,1,1,1,1]), r_4))
# Adds 1 to each column across every row

[[91 86 82 79 69]
 [73 24 61 37 49]
 [66 64 35 58 48]
 [42 51 89 87 92]]


In [21]:
print(np.add(np.array([[1],[1]]), r_4))
# Error: shape (2,1) can't broadcast with (4,5) — row count doesn't match

ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

Broadcasting lets NumPy add arrays of different shapes by stretching the smaller
one to match the larger one. The shapes must be compatible. Dimensions need to
either match or one of them needs to be 1.

## Rounding

In [22]:
print(r_3)

[[0.01516974]
 [0.36464491]]


In [23]:
print(np.trunc(r_3))   # drops the decimal, toward zero

[[0.]
 [0.]]


In [24]:
print(np.fix(r_3))     # same as trunc

[[0.]
 [0.]]


In [25]:
print(np.floor(r_3))   # rounds DOWN to nearest whole number

[[0.]
 [0.]]


In [26]:
print(np.ceil(r_3))    # rounds UP to nearest whole number

[[1.]
 [1.]]


In [27]:
print(np.round(r_3, 2))  # rounds to 2 decimal places

[[0.02]
 [0.36]]


## Cumulative Operations

In [28]:
print(r_4)

[[90 85 81 78 68]
 [72 23 60 36 48]
 [65 63 34 57 47]
 [41 50 88 86 91]]


In [29]:
print(np.sum(r_4))          # total of all values

1263


In [30]:
print(np.sum(r_4, axis=0))  # sum of each column

[268 221 263 257 254]


In [31]:
print(np.sum(r_4, axis=1))  # sum of each row

[402 239 266 356]


In [32]:
print(np.cumsum(r_4))       # rolling total of all values

[  90  175  256  334  402  474  497  557  593  641  706  769  803  860
  907  948  998 1086 1172 1263]


In [33]:
print(np.cumsum(r_4, axis=0))  # rolling total down each column

[[ 90  85  81  78  68]
 [162 108 141 114 116]
 [227 171 175 171 163]
 [268 221 263 257 254]]


## Grocery Problem

In [34]:
# Order: vegetables, fruits, snacks, beverages
bag1 = np.array([2, 3, 4, 0])
bag2 = np.array([4, 0, 1, 2])
print(bag1)
print(bag2)

[2 3 4 0]
[4 0 1 2]


In [35]:
totals = np.add(bag1, bag2)
print(f'The first bag contains {np.sum(bag1)} items, and the second bag contains {np.sum(bag2)} items.')

The first bag contains 9 items, and the second bag contains 7 items.


In [36]:
print(f'There are {totals[0]} vegetables, {totals[1]} fruits, {totals[2]} boxes of snacks, and {totals[3]} beverages in the two grocery bags.')

There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags.


## Teamwork

In [38]:
ali = np.array([5, 4, 6, 4, 2])

In [39]:
ben = np.array([0, 5, 5, 3, 4])
# Ben missed Monday so his value is 0

In [40]:
carla = np.array([3, 6, 0, 3, 4])
# Carla was sick Wednesday so her value is 0

In [41]:
all_knocks = np.array([ali, ben, carla])
print(all_knocks)

[[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [42]:
print(f'Ali knocked on {np.sum(ali)} doors, Ben knocked on {np.sum(ben)}, Carla knocked on {np.sum(carla)}.')
print(f'Total doors knocked: {np.sum(all_knocks)}')

Ali knocked on 21 doors, Ben knocked on 17, Carla knocked on 16.
Total doors knocked: 54


In [43]:
daily_totals = np.sum(all_knocks, axis=0)
rolling = np.cumsum(daily_totals)
estimated_votes = rolling * 0.5
print(estimated_votes)
# Every 2 knocks = 1 estimated vote, so multiply rolling total by 0.5

[ 4.  11.5 17.  22.  27. ]
